### ISSUE TITLE
autopull.sh download speed is too slow

### ISSUE THREAD

**Issue by huangjinshe** [roboticslibrary/libiconv#2]
I'm running:

> /autopull.sh --one-time

The pull speed too slow,  I set proxy before run this script but it won't use proxy.  any advice please?

**Comment by rickertm** [comment]
This repository focuses on CMake build scripts for libiconv. For issues with libiconv itself I would recommend to contact the upstream maintainers:
https://savannah.gnu.org/projects/libiconv/

The GNU portability library (gnulib) submodule can be found here:
https://savannah.gnu.org/projects/gnulib

**Comment by huangjinshe** [comment]
Sure, thanks.
